name: Statistics
markdown: kramdown
permalink: /Statistics/:year/:month/:day/:title

defaults:
  - scope:
      path: "_posts/Statistics"
    values:
      type: "Statistics"
  - scope:
      path: "_posts/Genetics"
    values:
      type: "work"
